-- =================================================================
-- FileVault Supabase PostgreSQL Database Schema
-- Run this in your Supabase Dashboard: SQL Editor -> New Query -> Run
-- =================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT,
  name TEXT,
  profile_image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. DOCUMENTS TABLE
CREATE TABLE IF NOT EXISTS public.documents (
  id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  original_name TEXT NOT NULL,
  document_type TEXT NOT NULL,
  sub_type TEXT,
  title TEXT,
  person_name TEXT,
  organization TEXT,
  recipient_name TEXT,
  institution TEXT,
  certificate_number TEXT,
  description TEXT,
  achievement TEXT,
  rank TEXT,
  storage_path TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  sha256 TEXT,
  issue_date DATE,
  expiry_date DATE,
  skills JSONB DEFAULT '[]'::jsonb,
  tags JSONB DEFAULT '[]'::jsonb,
  confidence NUMERIC DEFAULT 0,
  uncertain_fields JSONB DEFAULT '[]'::jsonb,
  verification_status TEXT DEFAULT 'Uploaded',
  processing_status TEXT DEFAULT 'uploaded',
  duplicate_status TEXT DEFAULT 'unique',
  duplicate_of_id TEXT,
  ai_processed BOOLEAN DEFAULT false,
  ai_raw_response JSONB,
  education_details JSONB,
  employment_details JSONB,
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMPTZ,
  is_pinned BOOLEAN DEFAULT false,
  pinned_at TIMESTAMPTZ,
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SHARES TABLE
CREATE TABLE IF NOT EXISTS public.shares (
  id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  owner_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  document_name TEXT NOT NULL,
  document_type TEXT NOT NULL,
  recipient_emails JSONB DEFAULT '[]'::jsonb,
  expires_at TIMESTAMPTZ,
  access_limit INTEGER,
  access_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'ACTIVE',
  allowed_fields JSONB DEFAULT '["documentType","institution","recipientName","issueDate","expiryDate","certificateNumber"]'::jsonb,
  permission TEXT DEFAULT 'both',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. AUDIT_LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  document_id TEXT REFERENCES public.documents(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  document_name TEXT,
  details JSONB,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'SUCCESS',
  ip_address TEXT
);

-- =================================================================
-- INDEXES FOR FAST QUERYING
-- =================================================================
CREATE INDEX IF NOT EXISTS idx_documents_owner_id ON public.documents(owner_id);
CREATE INDEX IF NOT EXISTS idx_documents_sha256 ON public.documents(sha256);
CREATE INDEX IF NOT EXISTS idx_documents_type ON public.documents(document_type);
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_at ON public.documents(uploaded_at DESC);

CREATE INDEX IF NOT EXISTS idx_shares_document_id ON public.shares(document_id);
CREATE INDEX IF NOT EXISTS idx_shares_owner_id ON public.shares(owner_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON public.audit_logs(timestamp DESC);

-- =================================================================
-- AUTH SYNCHRONIZATION: BACKFILL & AUTO-SYNC FROM auth.users
-- =================================================================
-- 1) Backfill existing Supabase Auth users into public.users
INSERT INTO public.users (id, username, email, name, created_at, updated_at)
SELECT 
  id::text,
  COALESCE(raw_user_meta_data->>'username', split_part(email, '@', 1), id::text),
  email,
  COALESCE(raw_user_meta_data->>'name', raw_user_meta_data->>'full_name', email),
  created_at,
  COALESCE(updated_at, created_at)
FROM auth.users
ON CONFLICT (id) DO UPDATE SET
  email = EXCLUDED.email,
  updated_at = NOW();

-- 2) Auto-sync trigger for future Auth signups
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, username, email, name, created_at, updated_at)
  VALUES (
    NEW.id::text,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1), NEW.id::text),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', NEW.email),
    NEW.created_at,
    COALESCE(NEW.updated_at, NEW.created_at)
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Service Role full access policies (for backend serverless lambdas using service_role key)
DROP POLICY IF EXISTS "Service role full access to users" ON public.users;
CREATE POLICY "Service role full access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access to documents" ON public.documents;
CREATE POLICY "Service role full access to documents" ON public.documents FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access to shares" ON public.shares;
CREATE POLICY "Service role full access to shares" ON public.shares FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access to audit_logs" ON public.audit_logs;
CREATE POLICY "Service role full access to audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);

-- Authenticated user policies (direct Supabase client calls)
DROP POLICY IF EXISTS "Users can read/write own user record" ON public.users;
CREATE POLICY "Users can read/write own user record" ON public.users 
  FOR ALL USING (auth.uid()::text = id) WITH CHECK (auth.uid()::text = id);

DROP POLICY IF EXISTS "Users can read/write own documents" ON public.documents;
CREATE POLICY "Users can read/write own documents" ON public.documents 
  FOR ALL USING (auth.uid()::text = owner_id) WITH CHECK (auth.uid()::text = owner_id);

DROP POLICY IF EXISTS "Users can read/write own shares" ON public.shares;
CREATE POLICY "Users can read/write own shares" ON public.shares 
  FOR ALL USING (auth.uid()::text = owner_id) WITH CHECK (auth.uid()::text = owner_id);

DROP POLICY IF EXISTS "Public can view active shares" ON public.shares;
CREATE POLICY "Public can view active shares" ON public.shares 
  FOR SELECT USING (status = 'ACTIVE');

DROP POLICY IF EXISTS "Users can view own audit logs" ON public.audit_logs;
CREATE POLICY "Users can view own audit logs" ON public.audit_logs 
  FOR SELECT USING (auth.uid()::text = user_id);
